### ISSUE TITLE
Small typo in index.html

### ISSUE THREAD

**Issue by nathanj3** [SandiCal/morrowplots#2]
Currently, the last line on the landing page says: "Published dataset in the Illinios Data Bank doi.org/10.13012/B2IDB-7865141_V1 "

I'd suggest changing it to "Published dataset in the [Illinois Data Bank](doi.org/10.13012/B2IDB-7865141_V1)" by fixing the typo in 'Illinois' and making the doi a hyperlink.

**Comment by 1heidi** [comment]
Thank you, Nathan! I corrected the typo. The readme pulls from documentation for help() so I couldn't directly add the hyperlink, but Sandi just released V2 so it was a good timing as we update that throughout.

**Comment by nathanj3** [comment]
[like]  Jeffery, Nathan Reed reacted to your message:
________________________________
